"""update field close_date

Revision ID: bdc71744b1bc
Revises: e9d63d522f83
Create Date: 2024-09-10 17:07:50.256084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc71744b1bc'
down_revision = 'e9d63d522f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
